[aed, afn, all, ang, aoa, ars, aud, awg, bbd, bdt, bgn, bhd, bif, bmd, bnd, bob, brl,
  bsd, btn, bwp, bzd, cad, chf, clp, cny, cop, crc, cup, cve, czk, djf, dkk, dop,
  dzd, ecs, eek, egp, etb, eur, fjd, fkp, frf, gbp, ghc, gip, gmd, gnf, gtq, gyd,
  hkd, hnl, hrk, htg, huf, idr, ils, inr, iqd, irr, isk, jmd, jod, jpy, kes, khr,
  kmf, kpw, krw, kwd, kyd, kzt, lak, lbp, lkr, lrd, lsl, ltl, lvl, lyd, mad, mgf,
  mmk, mnt, mop, mro, mur, mvr, mwk, mxn, myr, mzm, mzn, nad, ngn, nio, nok, npr,
  nzd, omr, pab, pen, pgk, php, pkr, pln, pyg, qar, rol, ron, rsd, rub, sar, sbd,
  scr, sdd, sek, sgd, shp, skk, sll, sos, srd, srg, std, svc, syp, szl, thb, tnd,
  top, try, ttd, twd, tzs, uah, ugx, uyu, veb, vnd, vuv, wst, xaf, xcd, xof, xpf,
  zar, zmk, zwd]
