[mmk, brl, ugx, isk, ron, hrk, sbd, pyg, all, gbp, bzd, mwk, cup, irr, std, frf, mro,
  lsl, fjd, sdd, gmd, khr, yer, gtq, xaf, ecs, mxn, skk, etb, ltl, ghs, bdt, bob,
  rwf, mkd, clp, zar, vuv, cad, krw, ghc, sek, mad, sdg, lak, tnd, azm, xof, pen,
  szl, uyu, gel, cny, cve, pab, eur, mzn, idr, lvl, uzs, ang, npr, crc, jod, zmk,
  mur, bhd, mdl, ars, dkk, try, mzm, eek, tmt, nio, tjs, lkr, gnf, bgn, xpf, kyd,
  tmm, aed, inr, nok, shp, byr, hkd, gyd, rol, scr, veb, ngn, iqd, qar, myr, mga,
  kmf, sll, rsd, uah, kes, bsd, jmd, nzd, bmd, aud, svc, twd, htg, bam, lbp, cop,
  djf, kpw, lyd, srd, lrd, sos, sar, php, mop, vef, syp, afn, kgs, pln, bif, tzs,
  srg, czk, kwd, cdf, mvr, top, awg, vnd, pkr, kzt, hnl, pgk, xcd, dzd, nad, azn,
  aoa, btn, jpy, chf, wst, dop, rub, mgf, amd, bnd, ttd, huf, fkp, gip, zwd, zmw,
  bbd, thb, mnt, omr, bwp, ils, sgd, egp]
